### ISSUE TITLE
Play sounds upon pressing the joystick button, instead of releasing?

### ISSUE THREAD

**Issue by jack2game** [Joris-van-der-Wel/microswitch#1]
Hi, is it possible to edit anywhere in the config file such that the application plays sound upon pressing a button on joystick, instead of releasing the button?

Thanks!

**Comment by Joris-van-der-Wel** [comment]
Hi, sorry for the late reply, was dealing with some health issues.

I released a new version which reacts on joystick button press instead of release: https://github.com/Joris-van-der-Wel/microswitch/releases/tag/v3.0.0

Have fun!
